### Read book-lists created by a user
GET http://localhost:8081/api/user/1/book-lists/
Accept: application/json

### Read book-lists by id
GET http://localhost:8081/api/book-lists/ccccddd
Accept: application/json

###